server:
  port: 2000

spring:
  application:
    name: grab-booking-service
  config:
    activate:
      on-profile: dev
  data:
    mongodb:
      uri: ${MONGO_PREFIX}://${MONGO_BOOKING_USERNAME}:${MONGO_BOOKING_PASSWORD}@${MONGO_BOOKING_URL}

jwt:
  secret: ${JWT_SECRET}