apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    app: grab-booking-service
  name: grab-booking-service
  namespace: grab-car
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grab-booking-service
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: grab-booking-service
    spec:
      containers:
        - image: ervincode/grabcar-booking-service:${IMAGE_TAG}
          imagePullPolicy: Always
          name: grabcar-booking-service
          env:
            - name: ENV
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: SPRING_PROFILES_ACTIVE
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: app-config
                  key: PORT_AUTH_SERVICE
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secrets
                  key: JWT_SECRET
            - name: MONGO_PREFIX
              valueFrom:
                secretKeyRef:
                  name: mongodb-booking
                  key: MONGO_PREFIX
            - name: MONGO_BOOKING_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mongodb-booking
                  key: MONGO_BOOKING_USERNAME
            - name: MONGO_BOOKING_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mongodb-booking
                  key: MONGO_BOOKING_PASSWORD
            - name: MONGO_BOOKING_URL
              valueFrom:
                secretKeyRef:
                  name: mongodb-booking
                  key: MONGO_BOOKING_URL

---
#services
apiVersion: v1
kind: Service
metadata:
  labels:
    app: grab-booking-service
  name: grab-booking-service
  namespace: grab-car
spec:
  ports:
    - port: 2000
      protocol: TCP
      targetPort: 2000
  selector:
    app: grab-booking-service
  sessionAffinity: None
  type: ClusterIP